### ISSUE TITLE
Rewrite Importers

### ISSUE THREAD

**Issue by hunterowens** [codeforamerica/somerville-teacher-tool#211]
Because the current model gets progressively slower with the lookup, going to need to do some sort of postgres COPY, temp table validation, then copy over method. I'll take a stab at this in the next week, but want to make that I'm tracking the right branch? Has the new assessment model and tests been merged into master yet?

**Comment by alexsoble** [comment]
@hunterowens Merged! Via #209.

**Comment by alexsoble** [comment]
@hunterowens Will try to tackle this on Thursday/Friday, handling some bugs & performance improvements on the front-end today & tomorrow.

**Comment by alexsoble** [comment]
@hunterowens — I'm looking into these approaches: 

* https://github.com/tilo/smarter_csv
* https://github.com/ohler55/oj
* https://xjlin0.github.io/tech/2015/05/25/faster-parsing-csv-with-parallel-processing/

Currently running the attendance task against Somerville's data so that we have a baseline to measure improvements again. Will let you know how fast/slow it clocks in.

**Comment by alexsoble** [comment]
@hunterowens 

Measuring how many rows the importer can import in 5 minutes.

__Baseline / current status__: 37081 rows in 5 minutes 

(measured from the beginning of the `import_locally` method on an `AttendanceImporter`)

**Comment by alexsoble** [comment]
https://github.com/codeforamerica/somerville-teacher-tool/commit/7dbe204509b31b7f70b62373a8407570c05b42f9: 58315 rows in 5 minutes

**Comment by hunterowens** [comment]
:+1: :zap: :100: 

You'll probably get 2x that by limiting the db queries. Nice Job and enjoy the weekend.

**Comment by alexsoble** [comment]
Cut time in half for CSV, cut time by 40% for JSON via #227.
