### ISSUE TITLE
Interventions interface V2

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#312]
Invision: https://projects.invisionapp.com/share/KW43V95BT

**Comment by marimuraki** [comment]
@alexsoble: Comments based testing interventions-interface-v2 branch

1. The "Interventions" tab is not obvious. Even though I knew what the V2 design looked like already going in, I still got confused and missed the "Interventions". It was not obvious it was a tab and not just text that is clickable. 

Can the unselected tab be outlined or colored in some way that makes it more obviously a tab?

<img width="528" alt="screenshot 2015-10-22 12 29 59" src="https://cloud.githubusercontent.com/assets/1334815/10676088/c93e59b8-78b8-11e5-92bf-bcde246ef9c3.png">

<img width="520" alt="screenshot 2015-10-22 12 31 54" src="https://cloud.githubusercontent.com/assets/1334815/10676112/e74ee9e0-78b8-11e5-914e-4ad12999820b.png">

**Comment by marimuraki** [comment]
@alexsoble: Comments based testing interventions-interface-v2 branch

2. If you add interventions from the student's interventions tab and add a new intervention, the input from the prior add is not cleared from the text boxes.

For example:

1. I added "Phone Call" intervention
2. I clicked on "Add Intervention" to add new intervention
3. The content I added to my prior "Phone Call" intervention is shown rather than a clear / empty text box.

<img width="996" alt="screenshot 2015-10-22 12 37 02" src="https://cloud.githubusercontent.com/assets/1334815/10676288/113516de-78ba-11e5-91ac-f52fbaf24f0c.png">

**Comment by marimuraki** [comment]
@alexsoble: Comments based testing interventions-interface-v2 branch

Issue: **Indication that intervention has been added**

I noticed this when Colette was adding interventions in V1. She kept on clicking on "Save" because it wasn't clear that the intervention was added.

I did the same thing because I wasn't sure if the intervention got saved or my internet was slow and so I kept on clicking "Save". I didn't want to save my input so I opened up a new window to see if my interventions went through ... and I saw this:

<img width="404" alt="screenshot 2015-10-22 12 44 30" src="https://cloud.githubusercontent.com/assets/1334815/10676446/11eea080-78bb-11e5-85e9-b423c104f022.png">

So my interventions were being saved but since I had no confirmation of this, I kept clicking (similar to what Colette did) and ended up with duplicates.

**Comment by marimuraki** [comment]
@alexsoble: Comments based testing interventions-interface-v2 branch

**Issue: Keep formatting**

This is an issue that @jsgeiser first noticed when adding interventions last week. She was adding content in paragraph and bullet forms but the formatting was not retained once she hit "Save". Instead all of the text bunched up into a blob. @jsgeiser: feel free to add anything else I may be missing from your feedback.

I tested this myself and as you can see, the formatting is not kept.

**Before Save**
<img width="548" alt="screenshot 2015-10-22 12 43 39" src="https://cloud.githubusercontent.com/assets/1334815/10676558/05767aca-78bc-11e5-9ede-48c6b61d4448.png">

**After Save**
<img width="994" alt="screenshot 2015-10-22 12 49 25" src="https://cloud.githubusercontent.com/assets/1334815/10676485/5dd6a2e0-78bb-11e5-8862-7d2b7c9ca21f.png">

**Comment by marimuraki** [comment]
@alexsoble: Comments based testing interventions-interface-v2 branch

**Bug?**

I entered text in the "Goal" section ...

<img width="274" alt="screenshot 2015-10-22 12 57 50" src="https://cloud.githubusercontent.com/assets/1334815/10676680/b5ea2eb0-78bc-11e5-8c34-6ecf8367ebd5.png">

But it doesn't appear once saved.

<img width="271" alt="screenshot 2015-10-22 12 58 03" src="https://cloud.githubusercontent.com/assets/1334815/10676677/b0d4d9ac-78bc-11e5-851d-939e8f033b12.png">

**Comment by marimuraki** [comment]
@alexsoble: Comments based testing interventions-interface-v2 branch

**Issue: Set rules on dates**

What do you think about setting logic on the dates so we make sure the inputs / data collected make sense? For example, end date cannot be before start date.

<img width="271" alt="screenshot 2015-10-22 13 00 20" src="https://cloud.githubusercontent.com/assets/1334815/10676742/1a5cf67a-78bd-11e5-8028-06709031143c.png">

**Comment by alexsoble** [comment]
@marimuraki Thank you for the thorough QA & comments!

Just pushed fixes to a few of the comments: making the tabs more visible, resetting intervention form after submit, and the issue with "Goal" not showing up.

Keeping formatting like paragraph breaks and bulleted lists will take more time to implement. We would need to accept user input as Markdown and display as HTML on the front-end.

**Comment by jsgeiser** [comment]
That's it - in a meeting (e.g. SST), when we are going through interventions, it might be easier to write them all in the intervention box rather than create separate interventions. In that case, it would be easier to read if the interventions were listed rather than running together.

**Comment by alexsoble** [comment]
@jsgeiser — Ooooh, interesting. One benefit to adding interventions separately is that it makes them easier to analyze if we have them as distinct events in the database. Processing natural language (like written lists) is very hard!

**Comment by jsgeiser** [comment]
That's a good point on the data analysis end. Entering a single intervention is not that cumbersome so it is doable in a fast-paced meeting if it is kept it separated out.

**Comment by alexsoble** [comment]
@jsgeiser: :+1: — I am working on a single-page design that should make the process quick! Can't wait to test this out at a SST meeting soon!

**Comment by jsgeiser** [comment]
Sounds good!

**Comment by marimuraki** [comment]
To keep track of issues checked off: 

:white_check_mark: Design tab

![screenshot 2015-10-26 11 23 37](https://cloud.githubusercontent.com/assets/1334815/10738315/10a2cc1c-7bd4-11e5-95f9-0c5e2ac2b204.png)

**Comment by marimuraki** [comment]
Will add separate --- for example: **Clear text box for new intervention** (partly resolved)

:white_check_mark: text box cleared after "Save"
:x: text box not cleared after "Cancel"
