### ISSUE TITLE
Use OR filters within categories on school overview dashboard

### ISSUE THREAD

**Issue by alexsoble** [codeforamerica/somerville-teacher-tool#378]

**Comment by kevinrobinson** [comment]
Paraphrasing from @jsgeiser over email:

> One question – when I click on multiple filter under one category, it won’t recognize that. (e.g. clicking on Free lunch and reduced lunch). Is there a way to click on more than one filter in a category?

**Comment by alexsoble** [comment]
Gracias @kevinrobinson & @jsgeiser — good description!

This feature is ready. It does slow things down a bit when lots of filters are involved, especially in IE, so I am going to do a few things to speed them up before I merge this in.

@kevinrobinson — Planning on caching aggregated + serialized student data for each school at the db level and also caching the results of filter queries at the JS level. Let me know if you have other thoughts or ideas!

**Comment by kevinrobinson** [comment]
@alexsoble nice!  :)  Yeah, server-side caching sounds like a great idea.  If that's too slow on initial load we could also precompute the response as a rake task each day, depending on how much would be involved to optimize all the querying.

JS-side, `this.filteredStudents()` gets computed multiple times in a single render pass, so that'd be a good place to start.  A simple way is to call the method once in `render` and then pass it to other methods, since right now they each compute it separately.  Also, the bottleneck might be more from reconciliation and rendering rather than the filtering per-se, so profiling like https://facebook.github.io/react/docs/perf.html or the web inspector timeline might help pinpoint what needs optimizing too.  Happy to help with any of this next week too!

**Comment by alexsoble** [comment]
@kevinrobinson — Great! Yeah, I noticed that `this.filteredStudents()` gets called lots. Will cut that down and measure the impact. Thanks for pointing me in that direction!
